"""empty message

Revision ID: fc17c10520e9
Revises: 8541ba657e22
Create Date: 2023-05-22 17:51:19.582845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc17c10520e9'
down_revision = '8541ba657e22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.add_column('links', sa.Column('short_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'short_link')
    op.drop_column('links', 'user_id')
    # ### end Alembic commands ###
